# Generated by Django 6.0 on 2025-12-23 12:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=50)),
                ('service_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['service'], name='App_service_service_93a6b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance_m', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nearest_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.services')),
            ],
        ),
    ]
