# Generated by Django 6.0 on 2025-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
