# Generated by Django 6.0 on 2025-12-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_services_service'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='services',
            name='App_service_service_93a6b9_idx',
        ),
    ]
